const MILLISECONDS_IN_SECOND = 1000
const MILLISECONDS_IN_MINUTE = 60 * MILLISECONDS_IN_SECOND
const MILLISECONDS_IN_HOUR = 60 * MILLISECONDS_IN_MINUTE
const MILLISECONDS_IN_DAY = 24 * MILLISECONDS_IN_HOUR
const MILLISECONDS_IN_WEEK = 7 * MILLISECONDS_IN_DAY
const MILLISECONDS_IN_MONTH = 30 * MILLISECONDS_IN_DAY
const MILLISECONDS_IN_YEAR = 365 * MILLISECONDS_IN_DAY

export const timeUnits = {
  second: MILLISECONDS_IN_SECOND,
  minute: MILLISECONDS_IN_MINUTE,
  hour: MILLISECONDS_IN_HOUR,
  day: MILLISECONDS_IN_DAY,
  week: MILLISECONDS_IN_WEEK,
  month: MILLISECONDS_IN_MONTH,
  year: MILLISECONDS_IN_YEAR
}
